# Build settings
highlighter: rouge

# Site settings
title: "Nie&Gao"
description: > # this means to ignore newlines until "email:"
   Anyway, life is elsewhere and we all know it.

email: niexiao@hotmail.com
# blog logo
logo: "/assets/images/avatar.jpg"
# blog cover
cover: "/assets/images/cover.jpg"
cover_post: "/assets/images/cover-post.jpg"
cover_about: "/assets/images/cover-about.jpg"
cover_book: "/assets/images/cover-book.jpg"
cover_collect: "/assets/images/cover-collect.jpg"
cover_slide: "/assets/images/cover-slide.jpg"
cover_archive: "/assets/images/cover-archive.jpg"


name: 'Nie&Gao'
author: 'Nie&Gao'
author_image: "/assets/images/avatar.jpg"

# paginate:	4
paginate:	4

url: "https://uestc-dpz.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon: archive
    url:  /archive

  - icon: files-o
    url:  /collect

  - icon: book
    url:  /book

  - icon: film
    url:  /slide

gems :
  - jekyll-paginate
